name: DUT Tests

on: [push, pull_request]

jobs:
  hil_tests:
    name: HIL testing
    runs-on: dut-testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python reqirements
        run: cd HIL && make install
      - name: Run Tests
        run: cd HIL && make test

  dut_tests:
    name: DUT testing
    runs-on: dut-testing
    needs: hil_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python reqirements
        run: make install
      - name: Run Tests
        run: make test
